version: '3'

services:
  apache:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: portfolio
    ports:
      - '80:80'
    volumes:
      - ./dist:/app
    restart: always