version: '3'

services:
  apache:
    image: httpd:latest
    build:
        context: .
        dockerfile: Dockerfile
    container_name: portfolio
    ports:
      - "1234:80"
    volumes:
      - ./dist:/usr/local/apache2/htdocs
    restart: always